Repository alielsokary/EventApp, pull requests merged in 2021-10, with the labels that each got.

#1 chore: add bitrise badge
  EventApp.xcodeproj/xcshareddata/xcschemes/EventApp.xcscheme
  README.md
Labels: size/L

#2 Add a Codacy badge to README.md
  README.md
Labels: size/XS

#6 feat: Implement Coordinator
  EventApp.xcodeproj/project.pbxproj
  EventApp/App/AppCoordinator.swift
  EventApp/App/AppDelegate.swift
  EventApp/App/SceneDelegate.swift
  EventApp/Base.lproj/Main.storyboard
  EventApp/Info.plist
  EventApp/Library/BaseCoordinator.swift
  EventApp/Library/Typealias.swift
  EventApp/Scenes/Splash/Coordinator/SplashCoordinator.swift
  EventApp/Scenes/Splash/SplashViewController.swift
Labels: size/L

#7 feat: implement event list
  EventApp.xcodeproj/project.pbxproj
  EventApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  EventApp/Assets.xcassets/AppIcon.appiconset/icon-1024.png
  EventApp/Assets.xcassets/AppIcon.appiconset/icon-120.png
  EventApp/Assets.xcassets/AppIcon.appiconset/icon-180.png
  EventApp/Assets.xcassets/AppIcon.appiconset/icon-40.png
  EventApp/Assets.xcassets/AppIcon.appiconset/icon-58.png
  EventApp/Assets.xcassets/AppIcon.appiconset/icon-60.png
  EventApp/Assets.xcassets/AppIcon.appiconset/icon-80.png
  EventApp/Assets.xcassets/AppIcon.appiconset/icon-87.png
  EventApp/Assets.xcassets/EventApp-icon.imageset/Contents.json
  EventApp/Assets.xcassets/EventApp-icon.imageset/Group 1-1.png
  EventApp/Assets.xcassets/EventApp-icon.imageset/Group 1.png
  EventApp/Assets.xcassets/arrow-right-icon.imageset/Contents.json
  EventApp/Assets.xcassets/arrow-right-icon.imageset/arrow-right-icon-1.png
  EventApp/Assets.xcassets/arrow-right-icon.imageset/arrow-right-icon.png
  EventApp/Assets.xcassets/calendar-icon.imageset/Contents.json
  EventApp/Assets.xcassets/calendar-icon.imageset/calendar-icon-1.png
  EventApp/Assets.xcassets/calendar-icon.imageset/calendar-icon.png
  EventApp/Assets.xcassets/event-app-title-icon.imageset/Contents.json
  EventApp/Assets.xcassets/event-app-title-icon.imageset/event-app-title-icon-1.png
  EventApp/Assets.xcassets/event-app-title-icon.imageset/event-app-title-icon.png
  EventApp/Assets.xcassets/star-filled-icon.imageset/Contents.json
  EventApp/Assets.xcassets/star-filled-icon.imageset/star-filled-icon-1.png
  EventApp/Assets.xcassets/star-filled-icon.imageset/star-filled-icon.png
  EventApp/Assets.xcassets/star-unfilled-icon.imageset/Contents.json
  EventApp/Assets.xcassets/star-unfilled-icon.imageset/star-unfilled-icon-1.png
  EventApp/Assets.xcassets/star-unfilled-icon.imageset/star-unfilled-icon.png
  EventApp/Base.lproj/LaunchScreen.storyboard
  EventApp/Base.lproj/Main.storyboard
  EventApp/Library/Extensions/String+Extension.swift
  EventApp/Library/Extensions/UIImageView+Extension.swift
  EventApp/Library/Typealias.swift
  EventApp/Models/EventTypes.swift
  EventApp/Scenes/Events/Coordinator/EventsCoordinator.swift
  EventApp/Scenes/Events/Service/EventsService.swift
  EventApp/Scenes/Events/View Model/EventViewModel.swift
  EventApp/Scenes/Events/View Model/EventsViewModel.swift
  EventApp/Scenes/Events/View/Cell/EventTableViewCell.xib
  EventApp/Scenes/Events/View/Cell/EventsTableViewCell.swift
  EventApp/Scenes/Events/View/EventsViewController.swift
  EventApp/Scenes/Splash/Coordinator/SplashCoordinator.swift
  EventApp/Scenes/Splash/SplashViewController.swift
  EventApp/Scenes/Splash/View/SplashViewController.swift
Labels: size/XL

#8 enhancement: Update UI of Event card
  EventApp.xcodeproj/project.pbxproj
  EventApp/Colors.xcassets/Contents.json
  EventApp/Colors.xcassets/background.colorset/Contents.json
  EventApp/Colors.xcassets/gold.colorset/Contents.json
  EventApp/Colors.xcassets/primary.colorset/Contents.json
  EventApp/Colors.xcassets/subtitles.colorset/Contents.json
  EventApp/Colors.xcassets/titles.colorset/Contents.json
  EventApp/Info.plist
  EventApp/Library/Extensions/RxSwift+Extension.swift
  EventApp/Library/Fonts/Roboto-Black.ttf
  EventApp/Library/Fonts/Roboto-Medium.ttf
  EventApp/Library/Fonts/Roboto-Regular.ttf
  EventApp/Library/Styling/Custom Component/EALabel.swift
  EventApp/Library/Styling/EADesignSystem.swift
  EventApp/Library/Typealias.swift
  EventApp/Scenes/Events/View Model/EventViewModel.swift
  EventApp/Scenes/Events/View/Cell/EventTableViewCell.xib
  EventApp/Scenes/Events/View/Cell/EventsTableViewCell.swift
  EventApp/Scenes/Events/View/EventsViewController.swift
Labels: size/XL

#9 feat: Implement Event Details
  EventApp.xcodeproj/project.pbxproj
  EventApp/Assets.xcassets/arrow-left-icon.imageset/Contents.json
  EventApp/Assets.xcassets/arrow-left-icon.imageset/arrow-left-icon-1.png
  EventApp/Assets.xcassets/arrow-left-icon.imageset/arrow-left-icon.png
  EventApp/Assets.xcassets/placeholder-icon.imageset/Contents.json
  EventApp/Assets.xcassets/placeholder-icon.imageset/placeholder-icon.png
  EventApp/Base.lproj/Main.storyboard
  EventApp/Library/Extensions/MKMapView+Extension.swift
  EventApp/Library/Extensions/RxSwift+Extension.swift
  EventApp/Library/Extensions/UIImageView+Extension.swift
  EventApp/Library/Styling/EADesignSystem.swift
  EventApp/Scenes/Event Details/View Model/EventDetailsViewModel.swift
  EventApp/Scenes/Event Details/View/EventDetailsViewController.swift
  EventApp/Scenes/Event Details/ViewModel/EventDetailsCoordinator.swift
  EventApp/Scenes/Events/Coordinator/EventsCoordinator.swift
  EventApp/Scenes/Events/View Model/EventViewModel.swift
  EventApp/Scenes/Events/View/Cell/EventsTableViewCell.swift
Labels: size/L

#13 feat: Implement Event Types
  EventApp.xcodeproj/project.pbxproj
  EventApp.xcodeproj/xcshareddata/xcschemes/EventApp.xcscheme
  EventApp/Base.lproj/Main.storyboard
  EventApp/Scenes/Event Details/Coordinator/EventDetailsCoordinator.swift
  EventApp/Scenes/Event Types/View Model/EventTypeViewModel.swift
  EventApp/Scenes/Event Types/View/EventTypeCollectionViewCell.swift
  EventApp/Scenes/Event Types/View/EventTypeCollectionViewCell.xib
  EventApp/Scenes/Events/Service/EventsService.swift
  EventApp/Scenes/Events/View Model/EventsViewModel.swift
  EventApp/Scenes/Events/View/EventsViewController.swift
Labels: size/L

#14 feat: Implement pagination feature to get next pages of event list
  EventApp/Scenes/Events/View Model/EventsViewModel.swift
  EventApp/Scenes/Events/View/EventsViewController.swift
Labels: size/M

#19 refactor: Storage Service
  EventApp.xcodeproj/project.pbxproj
  EventApp/Scenes/Events/Coordinator/EventsCoordinator.swift
  EventApp/Scenes/Events/View Model/EventViewModel.swift
  EventApp/Services/Storage/StorageManager.swift
  EventApp/Services/Storage/StorageService.swift
  EventApp/Services/Storage/StorageSession.swift
  EventAppTests/EventViewModelTests.swift
  EventAppTests/RealmServiceMock.swift
  README.md
Labels: size/L
